### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by Qinka** [CTeX-org/ctex-kit#247]
在 Travis-CI 上通过持续集成编译文档，之前一直是 用 xeCJK ＋ xelatex 干的（而且 Travis 提供的是 Ubuntu 12.x，上边的 TeXLive  一颗赛艇），今天抽筋，换 ctex。 然而，尽管 使用上了 Ubuntu 14.x，
还是无法正常编译，现在是 安装完 texlive 之后，用 tlmgr 安装 ctex geometry l3kernel latex fontspec fandol，然后尝试编译，但是会报错：
```
) (/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(/usr/share/texlive/texmf-dist/tex/latex/tools/indentfirst.sty)
(/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/config/xeCJK.cfg))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! xeCJK error: "key-unknown"
! 
! Sorry, but xeCJK/options does not have a key called `LoadFandol'.
! 
! The key `LoadFandol' is being ignored.
! 
! See the xeCJK documentation for further information.
! 
! Type <return> to continue.
!...............................................  
                                                  
l.39   }
```

这个是 Travis 的脚本（.travis.yml)文件
```yaml
# To build what is need
sudo: required
dist: trusty
before_install:
  # 安装 XeTeX
  - "sudo apt-get update"
  - "sudo apt-get install -y --no-install-recommends wget texlive-base texlive-xetex latex-xcolor xzdec"
  - "sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - cd ~ && mkdir texmf
  - tlmgr init-usertree
  - sudo tlmgr update --all
  - sudo tlmgr install ctex
  - sudo tlmgr install geometry
  - sudo tlmgr install l3kernel
  - sudo tlmgr install l3packages
  - sudo tlmgr install latex
  - sudo tlmgr install fontspec
  - sudo tlmgr install fandol
  - cd $TRAVIS_BUILD_DIR

script: # 重要的东西编译三遍
  - xelatex test.tex
  - xelatex test.tex
  - xelatex test.tex
  - echo "DONE"

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    cd ~
    git clone https://qinka:$GITHUB_API_KEY@github.com/DingoLab/DingoRelease.git
    cd DingoRelease
    export RELPATH=$(pwd)
    cp "$TRAVIS_BUILD_DIR"/*.pdf .
    git add .
    git commit -am"travis-ci $(date)"
    git push origin master
    cd ~
    sudo rm -rf $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
```

 [这个](https://api.travis-ci.org/jobs/131934045/log.txt?deansi=true) 是那个持续集成的输出文本

（：（）
 #［］
